### ISSUE TITLE
Python 401(k) Case Study flex model specification possible issue with .DoubleMLData object

### ISSUE THREAD

**Issue by gzhelev2020** [DoubleML/doubleml-for-py#104]
Hello,

in the Python 401(k) Case Study when entering the flexible model data into the dml.DoubleMLData object and then printing it, the y-variable (net_tfa) is seen in the x_cols even after it was specified as y_col. 

This leads to the lasso model on the flex specification not estimating the coefficient correctly. For some reason it is only an issue with the flex model, but not with the base model. This is a reacent issue. Last week it was working properly. 

See screenshot
![dml_flex_issue](https://user-images.githubusercontent.com/70018370/117859970-01ca4500-b290-11eb-8f3b-6725c130cbb9.JPG)

**Comment by MalteKurz** [comment]
* Thanks for this bug report. Presumably, this is caused by the already fixed #95.
* Could you please check which version of `DoubleML` you are using? The fix was included in release 0.2.2. So with the newest release and the dev version you should no longer observe this behavior.

**Comment by gzhelev2020** [comment]
that was the issie, thanks.
