### ISSUE TITLE
how to predict

### ISSUE THREAD

**Issue by MarkovSc** [DoubleML/doubleml-for-py#115]
Thanks for your contributions to this project. However, compared with EcomML, this method lack of usage for predict.

**Comment by PhilippBach** [comment]
@MarkovSc,

thanks for the feedback. As double machine learning is a framework that mainly focuses on estimation and inference of causal effects we put emphasis on providing these methods in our implementation in Python and R. In the future we may add some prediction functionalities as well.

Once more, thank you. 

Best, 

Philipp
