### ISSUE TITLE
[API Documentation]: missing } in the python bib entry

### ISSUE THREAD

**Issue by tmieno2** [DoubleML/doubleml-for-py#155]
### Describe the issue related to the API documentation

Thanks for the package. Just wanted to report a very minor issue. You are missing } at the end of the bib entry for Python.

@article{DoubleML2022Python,
  title   = {{DoubleML} -- {A}n Object-Oriented Implementation of Double Machine Learning in {P}ython},
  author  = {Philipp Bach and Victor Chernozhukov and Malte S. Kurz and Martin Spindler},
  journal = {Journal of Machine Learning Research},
  year    = {2022},
  volume  = {23},
  number  = {53},
  pages   = {1--6},
  url     = {http://jmlr.org/papers/v23/21-0862.html}
} <---- this one.

**Comment by MalteKurz** [comment]
Thanks for your report. It was fixed in https://github.com/DoubleML/doubleml-docs/pull/86 and will be deployed soon.
