### ISSUE TITLE
[Feature Request]: Request for individual scores from IRM model

### ISSUE THREAD

**Issue by shoepaladin** [DoubleML/doubleml-for-py#209]
### Describe the feature you want to propose or implement

Hello, I am trying to deep dive the ATE and ATT components of the DMl-IRM model. For example, the IRM ATE is:
$$g(1,X) - g(0,X) + \frac{D(Y-g(1,X)}{m(X)} - \frac{(1-D)()Y-g(0,X)}{1-m(X)} - \theta$$
I understand that since $\theta$ is a scalar, we just take the expectation over this score function. However, I am interested in using the individual estimates (everything except $\theta$) for CATE and HTE analysis. 

### Propose a possible solution or implementation

Allowing the estimated IRM model to output the individual scores. 

### Did you consider alternatives to the proposed solution. If yes, please describe

I think these estimates are already available because they can be called for [CATE estimation](https://docs.doubleml.org/stable/guide/heterogeneity.html#conditional-average-treatment-effects-cates). But this requires specifying a basis function to project the CATE estimates onto. Being able to call it directly from IRM model output would be great and more flexible.

**Comment by SvenKlaassen** [comment]
I am sorry for the late reponse.

The scores are already available via the `psi` attribute (see [IRM documentation](https://docs.doubleml.org/dev/api/generated/doubleml.DoubleMLIRM.html#doubleml.DoubleMLIRM)).

This is an adjusted example from the documentation
```
import numpy as np
import doubleml as dml
from doubleml.datasets import make_irm_data
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
np.random.seed(3141)
ml_g = RandomForestRegressor(n_estimators=100, max_features=20, max_depth=5, min_samples_leaf=2)
ml_m = RandomForestClassifier(n_estimators=100, max_features=20, max_depth=5, min_samples_leaf=2)
data = make_irm_data(theta=0.5, n_obs=500, dim_x=20, return_type='DataFrame')
obj_dml_data = dml.DoubleMLData(data, 'y', 'd')
dml_irm_obj = dml.DoubleMLIRM(obj_dml_data, ml_g, ml_m)
dml_irm_obj.fit()

scores = dml_irm_obj.psi
print(scores)
```

Regarding the CATE estimation: Remark that the estimation is based on on the projection of the score part 

$$\psi_b =g(1,X) - g(0,X) + \frac{D(Y-g(1,X)}{m(X)} - \frac{(1-D)()Y-g(0,X)}{1-m(X)}$$
of $\psi = \psi_a\theta + \psi_b$.

These parts can be accessed via the `psi_elements` attribute.

```
psi_b = dml_irm_obj.psi_elements["psi_b"]
print(psi_b)
```

I hope this can help you.

**Comment by shoepaladin** [comment]
Thanks for pointing this out! Closing this issue.
