### ISSUE TITLE
[Feature Request]: Expose last stage score function estimation

### ISSUE THREAD

**Issue by waaally** [DoubleML/doubleml-for-py#214]
### Describe the feature you want to propose or implement

Hi,

I heard some time back that there were plans for the final stage score function estimation to be exposed so that we can use our own predictions from our own ML models. Has that feature been completed, and if so, are there examples on how to use it? Thanks!

In addition, I was wondering whether there is a DML multi-period diff-in-diff formulation in literature, and if there is, where is it on your priority list?

**Comment by SvenKlaassen** [comment]
I am sorry, that this feature is not implemented yet as our priorities shifted a bit, but I am confident that we will continue to implement this in the near future. For which model are you interested in using external predictions?

For DML multi-period diff-in-diff one could apply the two period setting multiple times (if the data is large enough). Else I guess this would require sturctural assumptions such as linear panel models.

**Comment by waaally** [comment]
The models we use the most are the PLR and IRM model. I think Diff-in-diff would have quite a lot of use cases as well. Looking forward to it!

**Comment by SvenKlaassen** [comment]
Thanks. I think we can focus on these models first. I will keep this Issue updated if we have a presentable branch.

**Comment by waaally** [comment]
Thank you very much!!!
