### ISSUE TITLE
[Feature Request]: Allow to pass kwargs to BLP models

### ISSUE THREAD

**Issue by SvenKlaassen** [DoubleML/doubleml-for-py#270]
### Describe the feature you want to propose or implement

Allow pass arguments to the `fit()` method of `DoubleMLBLP`. 
This enables e.g. the use of different covariance types e.g. `fit(cov_type='HC0')` , see https://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.OLS.fit.html

This should then be supported by all `cate` and `gate` methods (and `capo` and `gapo`).

### Propose a possible solution or implementation

Allow for kwargs in `fit()`

**Comment by JanTeichertKluge** [comment]
- Use `cov_params()`
- Set default for covariance to `HC_0`
